#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# wait for db
echo "Waiting for DB"
python manage.py wait_for_db

# Apply database migrations
echo "Apply database migrations"
python manage.py migrate

# wait for celery
# python manage.py wait_for_celery <num_retries> <delay_seconds>
# python manage.py wait_for_celery 10 3

# wait for ldap
# python manage.py wait_for_ldap <num_retries> <delay_seconds>
# python manage.py wait_for_ldap 10 3

# Collect static files
echo "Collect static files"
python manage.py collectstatic --noinput

# Apply Transalations
# python manage.py compilemessages

gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker \
    --bind 0.0.0.0:$PORT \
    --chdir=/app/config
